apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reviews
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
      - name: reviews
        image: ACCOUNT.dkr.ecr.ap-south-1.amazonaws.com/reviews:v2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
